# Generated by Django 6.0 on 2026-02-16 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.FloatField()),
                ('conscientiousness', models.FloatField()),
                ('extraversion', models.FloatField()),
                ('agreeableness', models.FloatField()),
                ('neuroticism', models.FloatField()),
                ('personality_type', models.CharField(max_length=50)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
